import { Helpers, Metrics, Fonts, Colors } from "../../themes";
import { StyleSheet, Text, View, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  mapStyle: {
    width: Dimensions.get("window").width,
    height: "91%",
  },
  eventName: {
    fontSize: 15,
    width: 100,
    left: -130,
    top: 2,
  },

  modalChatMessage: {
    textAlign: "center",
    fontSize: 60,
    position: "relative",
    top: "20%",
  },
  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },

  modal2: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "25%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },
  logo: {
    position: "absolute",
    top: "-100%",
    left: "22%",
  },
  modalText: {
    alignSelf: "center",
    fontSize: 50,
    width: "75%",
    textAlign: "center",
  },
  mapModalEmojis: {
    textAlign: "center",
    fontSize: 60,
    position: "relative",
    top: "20%",
  },
  backButton: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "20%",
    height: "6.1%",
    alignSelf: "center",
    borderRadius: 15,
    padding: 2,
    margin: 1,
    top: -20,
    color: "white",
    backgroundColor: "white",
    borderColor: "rgba(240, 237, 228, 0.6)",
    borderWidth: 2,
  },
  hereButton: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "20%",
    height: 40,
    alignSelf: "center",
    borderRadius: 15,
    padding: 2,
    margin: 1,
    top: -62,
    position: "relative",
    left: 90,
    color: "white",
    backgroundColor: "white",
    borderColor: "rgba(240, 237, 228, 0.6)",
    borderWidth: 2,
  },
});
