import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";

export default StyleSheet.create({
  text: {
    ...Fonts.normal,
    color: Colors.text,
    textAlign: "left",
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  modalChatMessage: {
    textAlign: "center",
    fontSize: 60,
    position: "relative",
    top: "20%",
  },
  menu: {
    flexDirection: "row",
    justifyContent: "center",
    color: "white",
    marginTop: 5,
  },
  surface: {
    marginTop: 15,
    alignSelf: "center",
    width: "39%",
    height: 52,
    marginBottom: 30,
    backgroundColor: "rgba(38,153,251, 1)",
  },
  joinChatButton: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "35%",
    height: "22%",
    alignSelf: "center",
    borderRadius: 10,
    position: "relative",
    top: "-16%",
    color: "white",
  },
  mapModalEmojis: {
    textAlign: "center",
    fontSize: 60,
    position: "relative",
    top: "20%",
  },
  mapButton: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "35%",
    height: "6%",
    alignSelf: "center",
    borderRadius: 12,

    position: "relative",
    top: "-16%",
    color: "white",
    borderColor: "lightblue",
    borderWidth: 1,
  },
  headerText: {
    color: "white",
    ...Fonts.h4,
    position: "relative",
    top: "20%",
    textAlign: "center",
    letterSpacing: 2,
    textTransform: "uppercase",
  },

  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },
  modalText: {
    alignSelf: "center",
    fontSize: 50,
    width: "75%",
    textAlign: "center",
  },
  logo: {
    position: "absolute",
    top: "-130%",
    left: "22%",
  },
  card: {
    marginLeft: 20,
    marginRight: 21,
    marginTop: 10,
  },
  appHeader: {
    backgroundColor: "rgba(38,153,251, .4)",
    height: 70,
  },
  headerBackground: {
    backgroundColor: "rgba(202, 154, 154, 0.65)",
    height: "20%",
    width: "100%",
    position: "absolute",
    top: "0.3%",
  },

  cardAddress: {
    color: "gray",
    marginBottom: 5,
    marginTop: -7,
    fontSize: 15,
    marginLeft: 16,
  },
  cardImg: {
    width: "92%",
    height: 255,
    marginLeft: 16,
    marginRight: 10,
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 8,
  },
  cardDescription: {
    color: "gray",
    fontSize: 16.5,
    marginTop: 12,
    marginBottom: 25,
  },
  cardDate: {
    color: "gray",
    marginBottom: 15,
    marginTop: 3,
    marginLeft: 17,
  },

  cardTime: {
    color: "gray",
    marginBottom: 0,
    marginTop: "-9%",
    marginLeft: "66.5%",
  },
  image2: {
    width: "46%",
    alignSelf: "center",
    position: "relative",
    top: "3%",
    height: 175,
    borderRadius: 150,
    marginTop: 20,
    marginBottom: 0,
    backgroundColor: Colors.lightBlue,
  },
  eventImg: {
    width: 360,
    height: 250,
    flex: 1,
    position: "relative",
  },
});
