import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";
export default StyleSheet.create({
  // background: {
  //   backgroundColor: "white",
  // },
  container1: {
    backgroundColor: "white",
    marginTop: 40,
    marginBottom: "20%",
    marginLeft: 18,
    marginRight: 18,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 10,
  },
  containerBox: {
    marginRight: "20%",
    marginLeft: "13.5%",
    position: "relative",
    top: "-4.5%",
    backgroundColor: "rgba(38,153,251,0.6)",
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "rgba(38,153,251,0.1)",
    width: "72%",
    height: "19.5%",
  },
  loginBox: {
    fontSize: 23,
    marginTop: 20,
    color: "white",
    textAlign: "center",
  },
  firstname: {
    position: "relative",
    top: "-9.8%",
    left: "86%",
    width: "7%",
    height: "3.6%",
  },
  lastname: {
    position: "relative",
    top: "-10%",
    left: "84.2%",
    width: "12%",
    height: "4.7%",
  },

  email: {
    position: "relative",
    top: "-10%",
    left: "86%",
    width: "9.7%",
    height: "4.3%",
  },

  password: {
    position: "relative",
    top: "-10.6%",
    left: "85.8%",
    width: "10%",
    height: "4.7%",
  },
  textInput: {
    height: 20,
    marginTop: 20,
    marginLeft: 0,
    color: "#BEBEBE",
    marginLeft: 30,
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
    marginBottom: 30,
  },
  validators: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    top: "-7.6%",
  },
  button: {
    alignSelf: "center",
    ...Fonts.small,
    marginTop: "-8%",
  },
  login: {
    alignSelf: "center",
    ...Fonts.normal,
    marginBottom: "7%",
    marginTop: "-3%",
  },
  account: {
    marginTop: 15,
    ...Fonts.small,
    color: "#BEBEBE",
  },
  arrow: {
    width: 30,
    height: 40,
    position: "relative",
    top: -50,
    left: 15,
  },
  logo: {
    alignSelf: "center",
  },
});
