import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";

export default StyleSheet.create({
  colMain: {
    ...Helpers.fullWidth,
    width: 375,
    height: 667,
    backgroundColor: Colors.white,
    overflow: "hidden",
  },
  eventButton: {
    ...Fonts.normal,
    textAlign: "center",
    marginTop: 20,
    marginBottom: 50,
    marginHorizontal: 50,
  },
  eventFooter: {
    width: 300,
    alignContent: "center",
    justifyContent: "center",
    height: 70,
    backgroundColor: Colors.lightBlue,
    padding: Metrics.medium,
  },
  errorMsg: {
    ...Fonts.normal,
    alignContent: "center",
    justifyContent: "center",
    textAlign: "center",
    height: 70,
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 10,
    color: Colors.primary,
    padding: Metrics.medium,
    backgroundColor: Colors.lightBlue,
    fontSize: 15,
  },

  welcomeDiv: {
    width: 400,
    borderColor: "white",
    borderWidth: 4,
    position: "relative",
    alignSelf: "center",
    // left: "-1%",
    shadowColor: "gray",
    shadowOffset: {
      width: 1,
      height: 5,
    },
    shadowOpacity: 1.9,
    shadowRadius: 2.3,
    margin: 15,
    elevation: 6,
  },
  welcomeText: {
    color: Colors.blue,
    // textAlign: "center",
    fontSize: 25,
    letterSpacing: 4,
    fontWeight: "bold",
    width: 400,
    // ...Metrics.bottomMargin,
  },
  interests: {
    textAlign: "center",
    color: Colors.blue,
    ...Fonts.normal,
    fontWeight: "bold",
    ...Metrics.bottomMargin,
    shadowRadius: 1.65,
    margin: 15,
    elevation: 6,
    position: "relative",
    top: 5,
  },
  interestPoints: {
    textAlign: "center",
    color: Colors.blue,
    ...Fonts.normal,
    fontWeight: "bold",
    ...Metrics.bottomMargin,
    shadowRadius: 1.65,
    margin: 15,
    elevation: 6,
    position: "relative",
    top: "4%",
  },
  interestContainer: {
    flexDirection: "row",
  },
  specificInterest: {
    textAlign: "center",
    color: Colors.blue,
    ...Fonts.normal,
    fontWeight: "bold",
    ...Metrics.bottomMargin,
    shadowRadius: 1.65,
    margin: 15,
    elevation: 6,
    position: "relative",
    top: "4%",
    textDecorationLine: "underline",
  },
  // childInterest: {
  //   flex: 4,
  // },
  interest: {
    color: Colors.blue,
    textAlign: "center",
    alignSelf: "center",
    borderColor: Colors.blue,
    borderWidth: 1,
    borderRadius: 8,
    ...Metrics.smallVerticalPadding,
    ...Metrics.smallHorizontalPadding,
    marginRight: 10,
    width: 114,
    position: "relative",
    top: "-30%",
  },
  interestPt: {
    position: "relative",
    top: "20%",
    left: "10%",
    color: Colors.blue,
  },
});
