import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";

export default StyleSheet.create({
  card: {
    marginLeft: 20,
    marginRight: 21,
    marginTop: 10,
    marginBottom: -18,
  },
  appHeader: {
    backgroundColor: "rgba(38,153,251, .4)",
    height: 70,
  },
  headerBackground: {
    backgroundColor: "rgba(202, 154, 154, 0.65)",
    height: "20%",
    width: "100%",
    position: "absolute",
    top: "0.3%",
  },

  cardAddress: {
    color: "gray",
    marginBottom: 5,
    marginTop: -7,
    marginLeft: 20,
  },
  cardImg: {
    width: "92%",
    height: 255,
    marginLeft: 16,
    marginRight: 10,
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 3,
  },
  title: {
    marginLeft: 20,
    fontSize: 21.2,
    textTransform: "uppercase",
    marginBottom: 16,
    marginTop: 35,
    fontWeight: "500",
  },
  cardDescription: {
    color: "gray",
    marginTop: 12,
    marginBottom: 35,
  },
  cardDate: {
    color: "gray",
    marginBottom: 0,
    marginTop: 3,
    marginLeft: 20,
  },
  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },
  container1: {
    backgroundColor: "white",
    marginTop: 15,
    marginBottom: 20,
    marginLeft: 18,
    marginRight: 18,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 10,
  },
  modalText: {
    alignSelf: "center",
    fontSize: 50,
  },
  logo: {
    position: "absolute",
    top: "-29%",
    left: "22%",
  },
  image2: {
    width: "50%",
    alignSelf: "center",
    position: "relative",
    top: "3%",
    height: 175,
    borderRadius: 150,
    marginTop: 20,
    marginBottom: 0,
    backgroundColor: Colors.lightBlue,
  },
  eventImg: {
    width: 336,
    height: 250,
    flex: 1,
  },
  imageDiv: {
    marginTop: 10,
    marginBottom: 0,

    position: "relative",
    top: "15%",
    width: "25%",
    height: "82%",
  },
  wholeCardDiv: {
    width: "83.1%",
    height: "53%",
    position: "relative",
    left: "-0.5%",
    top: "5%",
    alignSelf: "center",
    borderColor: "lightblue",
    borderWidth: 4,
    shadowColor: "black",
    shadowOffset: {
      width: 10,
      height: 5,
    },

    shadowOpacity: 10.7,
    shadowRadius: 8.65,
    margin: 15,
  },
  singleEvent: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "29%",
    alignSelf: "center",
    borderRadius: 10,
    // padding: 2,
    // margin: 1,
    position: "relative",
    top: "-70%",
    color: "white",
  },
  surface: {
    marginTop: "-8.5%",
    width: "35%",
    left: "10%",
    height: 40,
  },
  surfaceMap: {
    marginTop: "-10.5%",
    marginBottom: 10,
    width: "35%",
    left: "55.3%",
    height: 40,
  },
  mapModalEmojis: {
    textAlign: "center",
    fontSize: 60,
    position: "relative",
    top: "20%",
  },
  mapButton: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    width: "35%",
    height: "6%",
    alignSelf: "center",
    borderRadius: 12,
    borderColor: "lightblue",
    borderWidth: 1,
    color: "white",
  },
  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },
  modalText: {
    alignSelf: "center",
    fontSize: 50,
  },

  logo: {
    position: "absolute",
    top: "-130%",
    left: "22%",
  },
  logo2: {
    position: "relative",
    top: -46,
    left: "22%",
  },
});
