import { StyleSheet } from "react-native";
import { Fonts, Colors } from "../../themes";

export default StyleSheet.create({
  // eventForm: {
  //   flex: 1,
  // },
  name: {
    ...Fonts.normal,
    textAlign: "center",
  },
  address: {
    ...Fonts.normal,
    textAlign: "center",
  },
  city: {
    ...Fonts.normal,
    textAlign: "center",
    position: "relative",
    top: "25%",
  },

  state: {
    ...Fonts.normal,
    textAlign: "center",
    position: "relative",
    top: "35%",
  },

  zip: {
    ...Fonts.normal,
    textAlign: "center",
    position: "relative",
    top: "30%",
  },

  date: {
    ...Fonts.normal,
    textAlign: "center",
    position: "relative",
    top: "32%",
  },

  time: {
    ...Fonts.normal,
    textAlign: "left",
    textAlign: "center",
    position: "relative",
    top: "32%",
  },

  description: {
    ...Fonts.normal,
    textAlign: "left",
    textAlign: "center",
    position: "relative",
    top: "70%",
  },
  eventImg: {
    alignSelf: "center",
    position: "relative",
    top: "-38%",
    height: 170,
    borderRadius: 150,
    width: "50%",
    alignSelf: "center",
    // marginTop: 20,
    marginBottom: 0,
    backgroundColor: Colors.lightBlue,
    borderColor: Colors.blue,
    borderRadius: 150,
    borderBottomColor: Colors.blue,
  },
  image: {
    width: "100%",
    alignSelf: "center",
    position: "relative",
    top: "3%",
    height: 220,
    borderRadius: 150,
    // marginTop: 20,
    marginBottom: 0,
    backgroundColor: Colors.lightBlue,
  },
  text: {
    ...Fonts.normal,
    color: Colors.text,
    textAlign: "left",
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  textInput: {
    width: "90%",
    height: 42,
    borderColor: "#009688",
    borderWidth: 1,
    backgroundColor: "#fff",
    color: Colors.blue,
    textAlign: "center",
  },
  addEvent: {
    ...Fonts.normal,
    backgroundColor: "rgba(38,153,251,1)",
    borderWidth: 0.5,
    alignSelf: "center",
    paddingBottom: 5,
    margin: 5,
    borderWidth: 2,
    borderColor: "rgba(38,153,251,1)",
    position: "relative",
    bottom: "30%",
  },
  camera: {
    position: "relative",
    bottom: "50%",
    left: "28%",
    width: 20,
    height: 20,
  },
  selectPic: {
    position: "relative",
    top: "-35%",
    left: "-25%",
  },
  takePic: {
    position: "relative",
    top: "-7.9%",
    width: 118,
    left: "10%",
  },
  category: {
    position: "relative",
    top: "32%",
    textAlign: "center",
    ...Fonts.normal,
  },
  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },

  image2: {
    width: "40%",
    alignSelf: "center",
    position: "relative",
    top: "3%",
    height: 140,
    borderRadius: 150,
    marginTop: 20,
    marginBottom: 0,
    backgroundColor: Colors.lightBlue,
  },

  modalText: {
    alignSelf: "center",
    fontSize: 50,
  },
  logo: {
    position: "absolute",
    top: "-50%",
    left: "22%",
  },

  field1: {
    backgroundColor: "white",
    width: "52%",
    // position: "relative",
    // top: "2%",
    margin: "5%",
    padding: "3%",
    height: "9%",
    alignSelf: "center",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    // backgroundColor:
  },
  field2: {
    backgroundColor: "white",
    margin: "5%",
    top: "-4%",
    padding: "3%",
    height: "9%",
    position: "relative",
    left: "-1%",
    width: "43%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
  },
  field3: {
    backgroundColor: "white",
    width: "43%",
    position: "relative",
    left: "54%",
    top: "-16.5%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
  },
  field4: {
    backgroundColor: "white",
    width: "44%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-13%",
    left: "3.8%",
  },
  field5: {
    backgroundColor: "white",
    width: "43%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-22%",
    left: "53.8%",
  },
  field6: {
    backgroundColor: "white",
    width: "44%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-19%",
    left: "3.8%",
  },
  field7: {
    backgroundColor: "white",
    width: "43%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-28%",
    left: "53.8%",
  },
  field8: {
    backgroundColor: "white",
    width: "44%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-25%",
    left: "3.8%",
  },
  field9: {
    backgroundColor: "white",
    width: "43%",
    height: "9%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: Colors.blue,
    position: "relative",
    top: "-34%",
    left: "53.8%",
  },
});
