import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";

export default StyleSheet.create({
  screenWrapper: {
    display: "flex",
    height: 600,
    width: 420,
    flex: 1,
    backgroundColor: Colors.lightBlue,
  },
  imageContainer: {
    ...Helpers.crossCenter,
    // backgroundColor: Colors.mediumBlue,
    ...Metrics.verticalPadding,
    borderRadius: 150,
    width: "70%",
    alignSelf: "center",
  },
  chatMessages: {
    display: "flex",
    alignItems: "center",
    // justifyContent: "center",
    top: 50,
    // height: 50,
    flexDirection: "row",
  },
  chatMessage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    height: 35,
    width: 80,
    borderWidth: 1,
    borderColor: "lightblue",
    borderRadius: 5,
    padding: "2%",
    marginLeft: 0,
  },
  chatMessageWrapper: {
    top: 20,
    // height: "100%",
    width: 395,
  },
  textInput: {
    height: 50,
    width: 395,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: "lightblue",
    position: "absolute",
    top: 400,
    left: 10,
    backgroundColor: Colors.lightBlue,
  },
  welcomeChat: {
    fontSize: 22,
    textAlign: "center",
  },
  userImage: {
    display: "flex",
    resizeMode: "cover",
    width: 40,
    height: 40,
    borderRadius: 10,
    borderColor: "white",
    margin: 3,
    marginLeft: 10,
  },
  sendMessageButton: {
    top: 370,
    left: 300,
    width: 100,
    borderWidth: 2,
    borderColor: "white",
    position: "absolute",
    backgroundColor: "white",
    borderRadius: 10,
  },
});
