import { StyleSheet } from "react-native";

export default StyleSheet.create({
  appHeader: {
    backgroundColor: "rgba(38,153,251, .4)",
    height: 70,
  },
  container1: {
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: "20%",
    marginLeft: 18,
    marginRight: 18,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 10,
  },
  email: {
    position: "relative",
    top: "-11.5%",
    left: "86.8%",
    width: "6%",
    height: "5%",
  },
  textInputEmail: {
    height: 26.5,
    marginTop: 80,
    color: "#4d4a4a",
    marginLeft: 30,
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
    marginBottom: 30,
  },
  password: {
    position: "relative",
    top: "-12%",
    left: "86.5%",
    width: "5%",
    height: "5%",
  },
  textInput: {
    height: 26.5,
    marginTop: 20,
    color: "#4d4a4a",
    marginLeft: 30,
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
    marginBottom: 30,
  },
  validators: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    top: "-11%",
    fontSize: 11,
  },
  button: {
    alignSelf: "center",
    fontSize: 12,
    marginBottom: "28%",
  },
});
