import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container1: {
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: "20%",
    marginLeft: 18,
    marginRight: 18,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 10,
  },
  appHeader: {
    backgroundColor: "rgba(38,153,251, .4)",
    height: 70,
  },
  textTime: {
    color: "#4d4a4a",
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
  },
  picOption: {
    flex: 2,
    marginTop: "-6%",
    marginLeft: "-2%",
    marginRight: "-3%",
  },
  surface1: {
    alignSelf: "center",
    width: "40%",
    height: 35,
    marginTop: 10,
    marginLeft: -160,
    marginBottom: 15,
  },
  surface2: {
    alignSelf: "center",
    width: "40%",
    height: 35,
    marginRight: -160,
    marginTop: -50,
    marginBottom: 15,
  },
  image: {
    marginTop: 30,
    marginBottom: 20,
    position: "relative",
    top: "-1%",
    width: "92%",
    height: 255,
    alignSelf: "center",
    borderWidth: 0.2,
    borderColor: "#BEBEBE",
  },

  textInputName: {
    height: 26.5,
    marginTop: 30,
    color: "#4d4a4a",
    marginLeft: 30,
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
  },
  validatorName: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    top: "-1.3%",
    fontSize: 11,
    marginBottom: 10,
  },
  name: {
    position: "relative",
    top: "-2%",
    left: "88%",
    color: "#4d4a4a",
  },
  validators: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    top: "-2%",
    fontSize: 11,
  },
  pin: {
    position: "relative",
    top: "-2.2%",
    left: "86.5%",
    color: "#4d4a4a",
  },
  textInput: {
    height: 26.5,
    marginTop: 15,
    color: "#4d4a4a",
    marginLeft: 30,
    marginRight: 30,
    borderColor: "#BEBEBE",
    letterSpacing: 1,
    textAlign: "left",
    fontSize: 16,
    borderBottomWidth: 1,
    width: "85%",
  },
  selectState: {
    left: 30,
    borderColor: "#BEBEBE",
    borderBottomWidth: 1,
    width: "85%",
    marginTop: 15,
    paddingBottom: 5,
  },
  date: {
    fontSize: 16,
    color: "rgba(38,153,251,1)",
  },
  selectDate: {
    left: 30,
    borderColor: "#BEBEBE",
    borderBottomWidth: 1,
    width: "85%",
    marginTop: 15,
    paddingBottom: 4,
  },
  validatorDate: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    top: "-1.7%",
    fontSize: 11,
    marginBottom: 10,
  },
  time: {
    fontSize: 16,
    color: "rgba(38,153,251,1)",
  },
  selectTime: {
    left: 30,
    borderColor: "#BEBEBE",
    borderBottomWidth: 1,
    width: "85%",
    paddingBottom: 4,
    marginTop: 10,
  },
  validatorTime: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    fontSize: 11,
    marginBottom: 10,
    top: "-1.8%",
  },
  validatorCategory: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    fontSize: 11,
    marginBottom: 10,
    top: "-1.6%",
  },
  validatorDescription: {
    marginLeft: 30,
    color: "#BEBEBE",
    position: "relative",
    fontSize: 11,
    marginBottom: 10,
    top: "-1.6%",
  },

  modal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    position: "absolute",
    top: "15%",
    height: "50%",
    bottom: 0,
    backgroundColor: "white",
  },
  modalText: {
    alignSelf: "center",
    fontSize: 50,
    width: "75%",
    textAlign: "center",
  },
  logo: {
    position: "absolute",
    top: "-130%",
    left: "22%",
  },
  image2: {
    width: "46%",
    alignSelf: "center",
    position: "relative",
    top: "3%",
    height: 175,
    borderRadius: 150,
    marginTop: 20,
    marginBottom: 0,
    backgroundColor: "#F1F9FF",
  },
});
