import { StyleSheet } from "react-native";
import { Helpers, Metrics, Fonts, Colors } from "../../themes";
export default StyleSheet.create({
  container: {
    backgroundColor: "rgb(233, 233, 233)",
    flex: 1,
  },
  logo: {
    alignSelf: "center",
  },
  background: {
    backgroundColor: "rgb(235, 233, 233)",
    position: "relative",
    top: 80,
  },
  button: {
    color: Colors.blue,
    borderWidth: 0.5,
    borderColor: Colors.blue,
    width: 300,
    padding: 10,
    margin: 2,
    backgroundColor: "rgba(188, 224, 253, 1)",
    alignSelf: "center",
  },

  continueButton: {
    backgroundColor: "rgba(38,153,251,1)",
    borderWidth: 0.5,
    alignSelf: "center",
    paddingTop: 10,
    ...Fonts.small,
    paddingBottom: 10,
    margin: 10,
    borderColor: "rgba(38,153,251,1)",
    position: "relative",
    top: 30,
    width: 342,
    height: 60,
  },

  buttonPress: {
    color: Colors.blue,
    borderWidth: 0.5,
    borderColor: Colors.blue,
    width: 300,
    padding: 10,
    margin: 2,
    backgroundColor: "white",
    alignSelf: "center",
  },

  login: {
    width: 550,
    position: "relative",
    top: 65,
    height: 60,
    alignSelf: "center",
    backgroundColor: "rgba(188, 224, 253, 1)",
    borderWidth: 0.5,
    paddingTop: 10,
    ...Fonts.normal,
    paddingBottom: 10,
    margin: 10,
    borderColor: "rgba(38,153,251,1)",
  },
  account: {
    ...Fonts.small,
    color: "black",
    position: "relative",
    top: 70,
  },
  header: {
    ...Fonts.h3,
    color: Colors.blue,
    padding: 3,
    margin: 3,
    alignSelf: "center",
    position: "relative",
    top: -50,
  },
  selectInterests: {
    // fill: 'rgba(255,255,255,1)',
    color: Colors.blue,
    borderWidth: 0.5,
    borderColor: Colors.blue,
    width: 300,
    padding: 10,
    margin: 2,
    backgroundColor: "white",
    alignSelf: "center",
  },

  arrow: {
    width: 30,
    height: 40,
    position: "relative",
    top: -50,
    left: 15,
  },
});
